import type { PreviewCredit } from './PreviewApp'
import { Button, Empty, Icon, PageTitle } from './ui'

export function PreviewCredits({ credits, selectedClaimNumber, currentClaims, navigate, onShowDocument }: { credits: PreviewCredit[]; selectedClaimNumber?: string; currentClaims: { number: string; termDate: string }[]; navigate: (page: string) => void; onShowDocument: (credit: PreviewCredit) => void }) {
  const selected = credits.find(credit => credit.claimNumber === selectedClaimNumber)
  const claimTarget = (number: string) => { const current = currentClaims.find(claim => claim.number === number); return current ? `claim:${current.termDate}` : `sample:${number}` }
  return <>
    {selected ? <button className="back-link" onClick={() => navigate(claimTarget(selected.claimNumber))}>← Zurück zur Meldung</button> : null}
    <PageTitle title={selected ? 'Gutschrift' : 'Gutschriften'} subtitle={selected ? `Zur Meldung ${selected.claimNumber}` : 'Alle fiktiven Gutschriften Ihrer Apotheke.'}/>
    {selected ? <section className="data-section"><div className="section-header"><h2>Beispielgutschrift</h2><span className="preview-count">Nur Demo</span></div><div className="term-summary"><div><span>Referenz</span><strong>{selected.reference}</strong></div><div><span>Bereitgestellt</span><strong>{selected.provided}</strong></div></div><p>Fiktives Dokumentmuster für das Kundengespräch. Es wurde keine Zahlung ausgeführt.</p><div className="claim-row-actions"><Button variant="secondary" onClick={() => onShowDocument(selected)}>Muster ansehen</Button><button className="text-button" onClick={() => navigate(claimTarget(selected.claimNumber))}>Meldung öffnen <Icon name="arrow" size={15}/></button></div></section> : credits.length ? <section className="data-section"><div className="table-wrap"><table><thead><tr><th>Meldung</th><th>Referenz</th><th>Bereitgestellt</th><th>Aktionen</th></tr></thead><tbody>{credits.map(credit => <tr key={credit.reference}><td>{credit.claimNumber}</td><td>{credit.reference}</td><td>{credit.provided}</td><td><div className="claim-row-actions"><Button variant="secondary" onClick={() => navigate(claimTarget(credit.claimNumber))}>Meldung ansehen</Button><button className="text-button" onClick={() => navigate(`credits:${credit.claimNumber}`)}>Gutschrift <Icon name="arrow" size={15}/></button></div></td></tr>)}</tbody></table></div></section> : <Empty title="Noch keine Gutschriften" description="Sobald eine Gutschrift verfügbar ist, erscheint sie hier."/>}
  </>
}
